### ISSUE TITLE
cgi.d: random "Bad file descriptor" exceptions

### ISSUE THREAD

**Issue by quickfur** [adamdruppe/arsd#113] opened 2017-09-25 23:21 UTC
I'm using `cgi.d` with `-version=embedded_httpd`, and running into intermittent `Bad file descriptor` errors, when load is high.  Here's an example console output when it happens:

````
std.socket.SocketOSException@std/socket.d(2948): Unable to obtain remote socket address: Bad file descriptor
----------------
??:? @property @trusted std.socket.Address std.socket.Socket.remoteAddress() [0x39d519c1]
??:? arsd.cgi.Cgi arsd.cgi.Cgi.__ctor(arsd.cgi.BufferedInputRange, bool*) [0x39cd0f38]
??:? void mm.__mixin20.__mixin1.customCgiMainImpl_.cgiMainImpl(immutable(char)[][]) [0x39ca847c]
??:? _Dmain [0x39ca89df]
````

Here's another sample:
````
Exception: Bad file descriptor
core.exception.AssertError@/mnt/1/home/hsteoh/prog/d/ext/arsd/cgi.d(1670): Assertion failure
----------------
??:? _d_assertp [0x39d35c51]
??:? void arsd.cgi.Cgi.setResponseStatus(immutable(char)[]) [0x39cd2296]
??:? void cgiapi.internalError(arsd.cgi.Cgi) [0x39ca9f34]
??:? void mm.cgiMain(arsd.cgi.Cgi) [0x39ca7f60]
??:? void mm.__mixin20.__mixin1.customCgiMainImpl_.cgiMainImpl(immutable(char)[][]) [0x39ca8555]
??:? _Dmain [0x39ca89df]
````

Sometimes my in-app exception catcher catches just this:
````
Exception: Bad file descriptor
````

A variety of manifestations, but it all seems to be related to bad file descriptors.  Where is this error coming from, and why is it happening?  Any tips how to track down this problem?  What am I doing wrong?

**Comment by adamdruppe** [comment] 2017-09-26 12:32
I've seen that happen before during benchmark tests, but never under my real world loads. Never figured out the real cause.....

I wonder if it just ran out of file descriptors. Maybe I'm not closing them appropriately and the benchmark thing is fast enough to catch up to it.

**Comment by adamdruppe** [comment] 2017-09-26 12:39
do you happen to know if the kernel holds on to the fd if close is called without shutdown for TIME_WAIT or something? I do seem to generally call close....

though the Socket destructor calls close too. Possible that it is being called twice - scope(failure) and a later GC cleanup I guess. The stack trace doesn't show that, but if the GC killed a Socket instance, it called close(fd), and then the fd was still referenced elsewhere in the program it could cause a delayed failure.

**Comment by quickfur** [comment] 2017-10-11 18:53
Sorry, haven't had time to track this down.  It's still happening intermittently, but just now something new happened (not sure if it's related, but I suspect it is).  I left the process running in the background for a while on a non-standard port (so no outside traffic), and suddenly it started printing repeated messages every second:

````
object.Exception@/mnt/1/home/hsteoh/prog/d/ext/arsd/cgi.d(3212): Resource temporarily unavailable
----------------
??:? void arsd.cgi.BufferedInputRange.popFront(ulong, ulong, bool) [0xff6b1428]
??:? arsd.cgi.Cgi arsd.cgi.Cgi.__ctor(arsd.cgi.BufferedInputRange, immutable(char)[], ushort, int, bool, void delegate(const(ubyte)[]), void delegate(), bool*) [0xff6aa43c]
??:? arsd.cgi.Cgi arsd.cgi.Cgi.__ctor(arsd.cgi.BufferedInputRange, bool*) [0xff6aa213]
??:? void mm.__mixin15.__mixin1.customCgiMainImpl_.cgiMainImpl(immutable(char)[][]) [0xff67c754]
??:? _Dmain [0xff67ccb7]
````

Killing the process and restarting made the errors go away.  Strange.

**Comment by quickfur** [comment] 2017-10-11 18:55
Actually, ignore that.  I misdirected an `nmap` probe to that port instead of another server I'm testing.  Sorry for the false alarm.

**Comment by quickfur** [comment] 2017-10-11 18:58
OTOH, perhaps it might be worth hardening `cgi.d` against socket connections that unexpectedly close prematurely, or HTTP requests that are unexpectedly truncated?  Upon some thought, perhaps that's the root of the problem here.

**Comment by adamdruppe** [comment] 2019-01-03 02:36
I *think* i have fixed this with the thread rewrite too... I think before it was saturating the broken thread worker distribution code and the new one is consistently much better. But since I was never able to consistently reproduce this it is hard to prove.

**Closed** 2019-10-18 22:22 UTC
