### ISSUE TITLE
Arsd:cgi server stall 

### ISSUE THREAD

**Issue by MrcSnm** [adamdruppe/arsd#383] opened 2023-04-30 14:35 UTC
I'm not able to produce a minimally reproducible example.

1: Clone https://github.com/MrcSnm/HipremeEngine
2: Run dub at tools/user/build_selector
3: Run the small setup and select the game as start_here
4: Run the webassembly build
5: Go to the folder `build/wasm` and run `dub` to start the cgi server
6: Run the build selector again, set the game as `test` and build webassembly
7: Reload the webpage and get a stall

**Comment by adamdruppe** [comment] 2023-11-29 20:59
This seems to be fixed as of version tag 11.x, though I was never able to reproduce before or after.

**Closed by adamdruppe** 2023-11-29 20:59 UTC
