### ISSUE TITLE
save .bmp? nanovega

### ISSUE THREAD

**Issue by EmTee70** [adamdruppe/arsd#146] opened 2018-03-10 17:16 UTC
Is there a way to save the content of an image to a file format that can be handled  by convert
(form ImageMagic).

**Comment by adamdruppe** [comment] 2018-03-10 17:19
On Sat, Mar 10, 2018 at 09:16:17AM -0800, Martin T. wrote:
> Is there a way to save the content of an image to a file format that can be handled  by convert
> (form ImageMagic).

I'll have to ask ketmar if he did that rendering backend yet.

But I think you can take a screenshot of the window externally and get it that way for now.

**Comment by EmTee70** [comment] 2018-03-10 17:43
Sure, but I want to shoot a sequence to make a film ;-)

**Comment by adamdruppe** [comment] 2018-03-10 23:38
yeah ketmar confirmed that isn't implemented yet but it is something he'd like to add at some point, either by pulling the texture back off the gpu or doing a software rasterizer.

**Comment by EmTee70** [comment] 2018-03-12 10:09
Would be cool. With this it might even be used to generate buttons or banners.

**Comment by EmTee70** [comment] 2018-03-12 10:13
p.s. off topic: Question: What is dpl in dpldocs meaning?
And hint: Add an favicon.ico it looks better in the browser tab.

**Comment by adamdruppe** [comment] 2018-03-12 11:57
On Mon, Mar 12, 2018 at 10:13:54AM +0000, Martin T. wrote:
> p.s. off topic: Question: What is dpl in dpldocs meaning?

dpl = D Programming Language

**Comment by adamdruppe** [comment] 2019-01-03 02:54
I am going to close this because it is in the vision idea... but not really on the roadmap. Still, the feature request is logged.

**Closed by adamdruppe** 2019-01-03 02:54 UTC
